# Generated by Django 4.2.11 on 2024-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(),
        ),
    ]
